# Generated by Django 5.2.13 on 2026-05-03 20:23

import inspect
import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def check_constraint_kwargs(condition: models.Q) -> dict[str, models.Q]:
    if "condition" in inspect.signature(models.CheckConstraint).parameters:
        return {"condition": condition}
    return {"check": condition}


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("media", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdaptationRelation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "relation_type",
                    models.CharField(
                        choices=[
                            ("source_to_adaptation", "Source to adaptation"),
                            ("adaptation_to_source", "Adaptation to source"),
                            ("remake", "Remake"),
                            ("alternate_version", "Alternate version"),
                            ("inspired_by", "Inspired by"),
                            ("audiobook_version", "Audiobook version"),
                            ("manga_to_anime", "Manga to anime"),
                            ("novel_to_film", "Novel to film"),
                            ("novel_to_show", "Novel to show"),
                        ],
                        default="source_to_adaptation",
                        max_length=48,
                    ),
                ),
                (
                    "completeness",
                    models.CharField(
                        choices=[
                            ("complete", "Complete"),
                            ("partial", "Partial"),
                            ("incomplete", "Incomplete"),
                            ("loose", "Loose"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=24,
                    ),
                ),
                (
                    "faithfulness_score",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "pacing_preservation_score",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "soul_preservation_score",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "recommended_experience_order",
                    models.CharField(
                        choices=[
                            ("read_first", "Read first"),
                            ("watch_first", "Watch first"),
                            ("listen_first", "Listen first"),
                            ("adaptation_sufficient", "Adaptation sufficient"),
                            ("source_preferred", "Source preferred"),
                            ("skip_adaptation", "Skip adaptation"),
                        ],
                        default="source_preferred",
                        max_length=32,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "adaptation_media_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adaptation_relations",
                        to="media.mediaitem",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adaptation_relations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_media_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_adaptation_relations",
                        to="media.mediaitem",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "-updated_at",
                    "source_media_item__title",
                    "adaptation_media_item__title",
                ],
                "indexes": [
                    models.Index(
                        fields=["owner", "relation_type"],
                        name="adapt_relation_owner_type_idx",
                    ),
                    models.Index(fields=["source_media_item"], name="adapt_relation_source_idx"),
                    models.Index(
                        fields=["adaptation_media_item"],
                        name="adapt_relation_adapt_idx",
                    ),
                    models.Index(
                        fields=["recommended_experience_order"],
                        name="adapt_relation_order_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        **check_constraint_kwargs(
                            models.Q(
                                ("source_media_item", models.F("adaptation_media_item")),
                                _negated=True,
                            )
                        ),
                        name="adapt_relation_distinct_media",
                    ),
                    models.UniqueConstraint(
                        fields=(
                            "owner",
                            "source_media_item",
                            "adaptation_media_item",
                            "relation_type",
                        ),
                        name="adapt_relation_owner_pair_type_uniq",
                    ),
                ],
            },
        ),
    ]
