# Generated by Django 5.2.13 on 2026-05-03 17:53

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("media", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscoveryTrail",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("theme", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                ("result_items", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discovery_trails",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_media_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="discovery_trails",
                        to="media.mediaitem",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "name"],
                "indexes": [
                    models.Index(
                        fields=["owner", "-created_at"],
                        name="discovery_owner_created_idx",
                    ),
                    models.Index(fields=["theme"], name="discovery_theme_idx"),
                ],
            },
        ),
    ]
