# Generated by Django 5.2.13 on 2026-05-03 18:43

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("candidates", "0002_candidateevaluation_narrative_signals"),
        ("media", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CouncilSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("prompt", models.TextField(blank=True)),
                ("context", models.JSONField(blank=True, default=dict)),
                ("critic_opinions", models.JSONField(blank=True, default=list)),
                (
                    "final_decision",
                    models.CharField(
                        choices=[
                            ("watch_now", "Watch now"),
                            ("sample", "Sample"),
                            ("delay", "Delay"),
                            ("skip", "Skip"),
                        ],
                        default="delay",
                        max_length=24,
                    ),
                ),
                ("final_explanation", models.TextField(blank=True)),
                (
                    "confidence_score",
                    models.PositiveSmallIntegerField(
                        default=50,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "disagreement_score",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("applied_to_candidate", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="council_sessions",
                        to="candidates.candidate",
                    ),
                ),
                (
                    "media_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="council_sessions",
                        to="media.mediaitem",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="council_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["owner", "-created_at"], name="council_owner_recent_idx"),
                    models.Index(
                        fields=["candidate", "-created_at"],
                        name="council_candidate_recent_idx",
                    ),
                    models.Index(
                        fields=["media_item", "-created_at"],
                        name="council_media_recent_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CriticPersona",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("key", models.SlugField(max_length=80)),
                ("name", models.CharField(max_length=120)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ruthless_critic", "Ruthless Critic"),
                            ("historian", "Historian"),
                            ("modern_defender", "Modern Defender"),
                            ("anime_specialist", "Anime Specialist"),
                            ("literary_editor", "Literary Editor"),
                            ("mood_doctor", "Mood Doctor"),
                            ("completion_strategist", "Completion Strategist"),
                            ("wildcard", "Wildcard"),
                        ],
                        max_length=40,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "weight",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="critic_personas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "name"],
                "indexes": [
                    models.Index(
                        fields=["owner", "is_enabled"],
                        name="critic_persona_enabled_idx",
                    ),
                    models.Index(fields=["role"], name="critic_persona_role_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("owner", "key"), name="critic_persona_owner_key_uniq"
                    ),
                    models.UniqueConstraint(
                        fields=("owner", "role"), name="critic_persona_owner_role_uniq"
                    ),
                ],
            },
        ),
    ]
