# Generated by Django 5.2.13 on 2026-05-01 21:32

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("movie", "Movie"),
                            ("tv_show", "TV show"),
                            ("anime", "Anime"),
                            ("novel", "Novel"),
                            ("audiobook", "Audiobook"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "release_year",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("known_creator", models.CharField(blank=True, max_length=255)),
                ("premise", models.TextField(blank=True)),
                ("source_of_interest", models.CharField(blank=True, max_length=255)),
                (
                    "hype_level",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "expected_genericness",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "expected_time_cost_minutes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unevaluated", "Unevaluated"),
                            ("watch_now", "Watch now"),
                            ("sample", "Sample"),
                            ("delay", "Delay"),
                            ("skip", "Skip"),
                        ],
                        default="unevaluated",
                        max_length=24,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at", "title"],
            },
        ),
        migrations.CreateModel(
            name="CandidateEvaluation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("watch_now", "Watch now"),
                            ("sample", "Sample"),
                            ("delay", "Delay"),
                            ("skip", "Skip"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "confidence_score",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                (
                    "likely_fit_score",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                (
                    "risk_score",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                ("reasons_for", models.JSONField(blank=True, default=list)),
                ("reasons_against", models.JSONField(blank=True, default=list)),
                ("best_mood", models.CharField(blank=True, max_length=160)),
                ("recommended_action", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluations",
                        to="candidates.candidate",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="candidate",
            index=models.Index(fields=["owner", "status"], name="candidate_owner_status_idx"),
        ),
        migrations.AddIndex(
            model_name="candidate",
            index=models.Index(fields=["media_type"], name="candidate_media_type_idx"),
        ),
        migrations.AddIndex(
            model_name="candidateevaluation",
            index=models.Index(
                fields=["candidate", "-created_at"], name="candidate_eval_recent_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="candidateevaluation",
            index=models.Index(fields=["decision"], name="candidate_eval_decision_idx"),
        ),
    ]
