# Generated by Django 5.2.13 on 2026-05-03 18:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("candidates", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidateevaluation",
            name="narrative_signals",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
