# Generated by Django 5.2.13 on 2026-05-03 19:59

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("candidates", "0002_candidateevaluation_narrative_signals"),
        ("media", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CanonSeason",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("moral_collapse", "Moral collapse"),
                            ("anti_heroes_done_right", "Anti-heroes done right"),
                            ("forgotten_masterpieces", "Forgotten masterpieces"),
                            ("modern_works_worth_it", "Modern works worth it"),
                            ("atmosphere_over_plot", "Atmosphere over plot"),
                            ("custom", "Custom"),
                        ],
                        default="custom",
                        max_length=48,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                        ],
                        default="planned",
                        max_length=24,
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("reflection_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="canon_seasons",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at", "title"],
            },
        ),
        migrations.CreateModel(
            name="CanonSeasonItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title_snapshot", models.CharField(max_length=255)),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("movie", "Movie"),
                            ("tv_show", "TV show"),
                            ("anime", "Anime"),
                            ("novel", "Novel"),
                            ("audiobook", "Audiobook"),
                        ],
                        max_length=24,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=1)),
                ("reason_included", models.TextField(blank=True)),
                ("what_to_pay_attention_to", models.TextField(blank=True)),
                (
                    "completion_status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("in_progress", "In progress"),
                            ("completed", "Completed"),
                            ("skipped", "Skipped"),
                        ],
                        default="planned",
                        max_length=24,
                    ),
                ),
                (
                    "canon_status",
                    models.CharField(
                        choices=[
                            ("unmarked", "Unmarked"),
                            ("personal_canon", "Personal canon"),
                            ("near_canon", "Near-canon"),
                            ("rejected", "Rejected"),
                            (
                                "historically_important",
                                "Historically important, not loved",
                            ),
                        ],
                        default="unmarked",
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="canon_season_items",
                        to="candidates.candidate",
                    ),
                ),
                (
                    "media_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="canon_season_items",
                        to="media.mediaitem",
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="canon.canonseason",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "created_at", "title_snapshot"],
            },
        ),
        migrations.AddIndex(
            model_name="canonseason",
            index=models.Index(fields=["owner", "status"], name="canon_season_owner_status_idx"),
        ),
        migrations.AddIndex(
            model_name="canonseason",
            index=models.Index(fields=["theme"], name="canon_season_theme_idx"),
        ),
        migrations.AddIndex(
            model_name="canonseasonitem",
            index=models.Index(fields=["season", "order"], name="canon_item_season_order_idx"),
        ),
        migrations.AddIndex(
            model_name="canonseasonitem",
            index=models.Index(fields=["completion_status"], name="canon_item_status_idx"),
        ),
        migrations.AddIndex(
            model_name="canonseasonitem",
            index=models.Index(fields=["canon_status"], name="canon_item_canon_status_idx"),
        ),
    ]
