# Generated by Django 5.2.13 on 2026-05-01 21:14

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("media", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TasteDimension",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=80)),
                ("description", models.TextField(blank=True)),
                (
                    "direction",
                    models.CharField(
                        choices=[("positive", "Positive"), ("negative", "Negative")],
                        default="positive",
                        max_length=16,
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taste_dimensions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MediaScore",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "media_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to="media.mediaitem",
                    ),
                ),
                (
                    "taste_dimension",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_scores",
                        to="taste.tastedimension",
                    ),
                ),
            ],
            options={
                "ordering": ["taste_dimension__name"],
            },
        ),
        migrations.AddIndex(
            model_name="tastedimension",
            index=models.Index(fields=["owner", "is_default"], name="taste_dim_owner_default_idx"),
        ),
        migrations.AddIndex(
            model_name="tastedimension",
            index=models.Index(fields=["slug"], name="taste_dimension_slug_idx"),
        ),
        migrations.AddConstraint(
            model_name="tastedimension",
            constraint=models.UniqueConstraint(
                fields=("owner", "slug"), name="taste_dimension_owner_slug_uniq"
            ),
        ),
        migrations.AddIndex(
            model_name="mediascore",
            index=models.Index(fields=["media_item"], name="media_score_item_idx"),
        ),
        migrations.AddIndex(
            model_name="mediascore",
            index=models.Index(fields=["taste_dimension"], name="media_score_dimension_idx"),
        ),
        migrations.AddConstraint(
            model_name="mediascore",
            constraint=models.UniqueConstraint(
                fields=("media_item", "taste_dimension"),
                name="media_score_item_dimension_uniq",
            ),
        ),
    ]
