# Generated by Django 5.2.13 on 2026-05-03 23:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("media", "0002_mediaitem_media_owner_type_status_idx_and_more"),
        ("taste", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="mediascore",
            index=models.Index(
                fields=["taste_dimension", "score"], name="media_score_dim_score_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mediascore",
            index=models.Index(
                fields=["media_item", "updated_at"], name="media_score_item_updated_idx"
            ),
        ),
    ]
