# Generated by Codex on 2026-05-09

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "module",
                    models.CharField(
                        choices=[
                            ("tonight", "Tonight Mode"),
                            ("candidate", "Candidate Evaluator"),
                            ("discovery", "Media Archaeologist"),
                            ("detox", "Completion Detox"),
                            ("aftertaste", "Aftertaste Log"),
                        ],
                        max_length=32,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=160)),
                ("state", models.JSONField(blank=True, default=dict)),
                ("latest_result", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["owner", "module", "-updated_at"], name="chat_owner_module_idx"
                    ),
                    models.Index(fields=["owner", "-updated_at"], name="chat_owner_updated_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("assistant", "Assistant"),
                            ("system", "System"),
                        ],
                        max_length=16,
                    ),
                ),
                ("content", models.TextField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chat.chatsession",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
                "indexes": [
                    models.Index(
                        fields=["session", "created_at"], name="chat_msg_session_created_idx"
                    ),
                ],
            },
        ),
    ]
