# Generated by Django 5.2.13 on 2026-05-03 22:48

import django.core.validators
from django.db import migrations, models

import canonos.accounts.models


def copy_preferred_scoring_strictness(apps, schema_editor) -> None:  # noqa: ANN001
    UserSettings = apps.get_model("accounts", "UserSettings")
    for settings in UserSettings.objects.all().only(
        "id",
        "preferred_scoring_strictness",
        "preferred_recommendation_strictness",
    ):
        settings.preferred_recommendation_strictness = settings.preferred_scoring_strictness
        settings.save(update_fields=["preferred_recommendation_strictness"])


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_usersettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="allow_modern_exceptions",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="burnout_sensitivity",
            field=models.PositiveSmallIntegerField(
                default=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="completion_detox_strictness",
            field=models.PositiveSmallIntegerField(
                default=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="default_tonight_available_minutes",
            field=models.PositiveIntegerField(
                default=90,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(1440),
                ],
            ),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="default_tonight_desired_effect",
            field=models.CharField(
                choices=[
                    ("comfort", "Comfort"),
                    ("quality", "Quality"),
                    ("surprise", "Surprise"),
                    ("light", "Light"),
                    ("deep", "Deep"),
                ],
                default="quality",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="default_tonight_energy_level",
            field=models.CharField(
                choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                default="medium",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="default_tonight_focus_level",
            field=models.CharField(
                choices=[("low", "Low"), ("medium", "Medium"), ("deep", "Deep")],
                default="medium",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="notification_preferences",
            field=models.JSONField(
                blank=True,
                default=canonos.accounts.models.default_notification_preferences,
            ),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="preferred_recommendation_strictness",
            field=models.PositiveSmallIntegerField(
                default=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="recommendation_formula_weights",
            field=models.JSONField(
                blank=True,
                default=canonos.accounts.models.default_recommendation_formula_weights,
            ),
        ),
        migrations.RunPython(copy_preferred_scoring_strictness, migrations.RunPython.noop),
    ]
