# Generated by Django 5.2.13 on 2026-05-03 23:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_usersettings_allow_modern_exceptions_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("actor_hash", models.CharField(blank=True, max_length=64)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("data_export_requested", "Data export requested"),
                            ("data_deletion_requested", "Data deletion requested"),
                            (
                                "account_deletion_requested",
                                "Account deletion requested",
                            ),
                            ("settings_updated", "Settings updated"),
                        ],
                        max_length=48,
                    ),
                ),
                ("request_id", models.CharField(blank=True, max_length=64)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["actor", "-created_at"], name="audit_actor_created_idx"),
                    models.Index(
                        fields=["event_type", "-created_at"],
                        name="audit_event_type_created_idx",
                    ),
                    models.Index(fields=["request_id"], name="audit_request_id_idx"),
                ],
            },
        ),
    ]
