# Generated by Django 5.2.13 on 2026-05-03 18:24

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("media", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NarrativeAnalysis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=24,
                    ),
                ),
                (
                    "character_complexity_score",
                    models.PositiveSmallIntegerField(
                        default=50,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "plot_complexity_score",
                    models.PositiveSmallIntegerField(
                        default=50,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "pacing_density_score",
                    models.PositiveSmallIntegerField(
                        default=50,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "thematic_weight_score",
                    models.PositiveSmallIntegerField(
                        default=50,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "moral_ambiguity_score",
                    models.PositiveSmallIntegerField(
                        default=50,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "atmosphere_score",
                    models.PositiveSmallIntegerField(
                        default=50,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "ending_dependency_score",
                    models.PositiveSmallIntegerField(
                        default=50,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "trope_freshness_score",
                    models.PositiveSmallIntegerField(
                        default=50,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "confidence_score",
                    models.PositiveSmallIntegerField(
                        default=35,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("analysis_summary", models.TextField(blank=True)),
                ("extracted_traits", models.JSONField(blank=True, default=list)),
                ("evidence_notes", models.TextField(blank=True)),
                (
                    "source_basis",
                    models.CharField(
                        choices=[
                            ("user_notes", "User notes"),
                            ("metadata", "Metadata"),
                            ("manual_analysis", "Manual analysis"),
                            ("mixed_notes_metadata", "Mixed notes and metadata"),
                            ("manual_correction", "Manual correction"),
                        ],
                        default="user_notes",
                        max_length=32,
                    ),
                ),
                (
                    "provider",
                    models.CharField(default="local_heuristic", max_length=64),
                ),
                (
                    "algorithm_version",
                    models.CharField(default="narrative-dna-v1", max_length=32),
                ),
                ("status_events", models.JSONField(blank=True, default=list)),
                ("error_message", models.TextField(blank=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "media_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="narrative_analyses",
                        to="media.mediaitem",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="narrative_analyses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(fields=["owner", "status"], name="narrative_owner_status_idx"),
                    models.Index(
                        fields=["media_item", "-updated_at"],
                        name="narrative_media_recent_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("owner", "media_item"),
                        name="narrative_owner_media_unique",
                    )
                ],
            },
        ),
    ]
