# Generated by Django 5.2.13 on 2026-05-02 00:08

import uuid

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("media", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalMetadata",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("movie_tv", "Movie/TV provider"),
                            ("anime", "Anime provider"),
                            ("book", "Book provider"),
                            ("audiobook", "Audiobook provider"),
                        ],
                        max_length=32,
                    ),
                ),
                ("provider_item_id", models.CharField(max_length=255)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                ("normalized_title", models.CharField(max_length=255)),
                ("normalized_description", models.TextField(blank=True)),
                ("image_url", models.URLField(blank=True)),
                ("source_url", models.URLField(blank=True)),
                (
                    "external_rating",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=4,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "external_popularity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "last_refreshed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "media_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_metadata",
                        to="media.mediaitem",
                    ),
                ),
            ],
            options={
                "ordering": ["-last_refreshed_at", "provider"],
                "indexes": [
                    models.Index(
                        fields=["provider", "provider_item_id"],
                        name="metadata_provider_id_idx",
                    ),
                    models.Index(
                        fields=["media_item", "provider"],
                        name="metadata_media_provider_idx",
                    ),
                    models.Index(
                        django.db.models.functions.text.Lower("normalized_title"),
                        name="metadata_title_lower_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("media_item", "provider", "provider_item_id"),
                        name="unique_media_external_metadata",
                    )
                ],
            },
        ),
    ]
