# Generated by Django 5.2.13 on 2026-05-01 21:03

import uuid

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("original_title", models.CharField(blank=True, max_length=255)),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("movie", "Movie"),
                            ("tv_show", "TV show"),
                            ("anime", "Anime"),
                            ("novel", "Novel"),
                            ("audiobook", "Audiobook"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "release_year",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("country_language", models.CharField(blank=True, max_length=120)),
                ("creator", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("consuming", "Consuming"),
                            ("completed", "Completed"),
                            ("paused", "Paused"),
                            ("dropped", "Dropped"),
                        ],
                        default="planned",
                        max_length=24,
                    ),
                ),
                (
                    "personal_rating",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=3,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                ("started_date", models.DateField(blank=True, null=True)),
                ("completed_date", models.DateField(blank=True, null=True)),
                ("runtime_minutes", models.PositiveIntegerField(blank=True, null=True)),
                ("episode_count", models.PositiveIntegerField(blank=True, null=True)),
                ("page_count", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "audiobook_length_minutes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at", "title"],
                "indexes": [
                    models.Index(fields=["owner", "status"], name="media_owner_status_idx"),
                    models.Index(fields=["media_type"], name="media_type_idx"),
                    models.Index(
                        django.db.models.functions.text.Lower("title"),
                        name="media_title_lower_idx",
                    ),
                ],
            },
        ),
    ]
