# Generated by Django 5.2.13 on 2026-05-03 23:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("media", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="mediaitem",
            index=models.Index(
                fields=["owner", "media_type", "status"],
                name="media_owner_type_status_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="mediaitem",
            index=models.Index(fields=["owner", "-updated_at"], name="media_owner_updated_idx"),
        ),
        migrations.AddIndex(
            model_name="mediaitem",
            index=models.Index(
                fields=["owner", "completed_date"], name="media_owner_completed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mediaitem",
            index=models.Index(fields=["owner", "personal_rating"], name="media_owner_rating_idx"),
        ),
    ]
