# Generated by Django 5.2.13 on 2026-05-01 21:41

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("candidates", "0001_initial"),
        ("media", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QueueItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("movie", "Movie"),
                            ("tv_show", "TV show"),
                            ("anime", "Anime"),
                            ("novel", "Novel"),
                            ("audiobook", "Audiobook"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("start_soon", "Start soon"),
                            ("sample_first", "Sample first"),
                            ("later", "Later"),
                        ],
                        default="start_soon",
                        max_length=24,
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                (
                    "estimated_time_minutes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("best_mood", models.CharField(blank=True, max_length=160)),
                ("queue_position", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="queue_items",
                        to="candidates.candidate",
                    ),
                ),
                (
                    "media_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="queue_items",
                        to="media.mediaitem",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="queue_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["queue_position", "-updated_at", "title"],
                "indexes": [
                    models.Index(
                        fields=["owner", "priority", "queue_position"],
                        name="queue_owner_priority_idx",
                    ),
                    models.Index(fields=["media_type"], name="queue_media_type_idx"),
                ],
            },
        ),
    ]
