# Generated by Django 5.2.13 on 2026-05-01 22:22

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("queueing", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TonightModeSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("available_minutes", models.PositiveIntegerField()),
                (
                    "energy_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "focus_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("deep", "Deep"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "desired_effect",
                    models.CharField(
                        choices=[
                            ("comfort", "Comfort"),
                            ("quality", "Quality"),
                            ("surprise", "Surprise"),
                            ("light", "Light"),
                            ("deep", "Deep"),
                        ],
                        max_length=24,
                    ),
                ),
                ("preferred_media_types", models.JSONField(blank=True, default=list)),
                (
                    "risk_tolerance",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "generated_recommendations",
                    models.JSONField(blank=True, default=list),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tonight_mode_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["owner", "-created_at"],
                        name="tonight_owner_created_idx",
                    ),
                    models.Index(
                        fields=["energy_level", "focus_level"],
                        name="tonight_energy_focus_idx",
                    ),
                ],
            },
        ),
    ]
