# Generated by Codex on 2026-05-04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("imports", "0001_initial"),
        ("media", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="importbatch",
            name="uploaded_file_reference",
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name="importbatch",
            name="file_size_bytes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="importbatch",
            name="progress_total",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="importbatch",
            name="progress_processed",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="importbatch",
            name="progress_percent",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="importbatch",
            name="error_message",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="importbatch",
            name="rollback_item_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="importbatch",
            name="rollback_error_message",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="importbatch",
            name="processed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="importbatch",
            name="rolled_back_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="importitem",
            name="created_object_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="importitem",
            name="duplicate_of_media_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="duplicate_import_items",
                to="media.mediaitem",
            ),
        ),
        migrations.AddField(
            model_name="exportjob",
            name="progress_total",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="exportjob",
            name="progress_processed",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="exportjob",
            name="progress_percent",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="exportjob",
            name="file_size_bytes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="exportjob",
            name="retention_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="exportjob",
            name="restore_validation",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="exportjob",
            name="processed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="importbatch",
            name="status",
            field=models.CharField(
                choices=[
                    ("previewed", "Previewed"),
                    ("processing", "Processing"),
                    ("confirmed", "Confirmed"),
                    ("rejected", "Rejected"),
                    ("rolled_back", "Rolled back"),
                    ("failed", "Failed"),
                ],
                default="previewed",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="importitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("valid", "Valid"),
                    ("invalid", "Invalid"),
                    ("duplicate", "Duplicate"),
                    ("imported", "Imported"),
                    ("skipped", "Skipped"),
                    ("rolled_back", "Rolled back"),
                ],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="exportjob",
            name="payload_text",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="exportjob",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued", "Queued"),
                    ("processing", "Processing"),
                    ("complete", "Complete"),
                    ("failed", "Failed"),
                ],
                default="complete",
                max_length=16,
            ),
        ),
    ]
