# Generated by Django 5.2.13 on 2026-05-03 19:10

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import canonos.evolution.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TasteEvolutionSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "snapshot_period",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("yearly", "Yearly"),
                        ],
                        default="monthly",
                        max_length=16,
                    ),
                ),
                ("snapshot_date", models.DateField()),
                (
                    "aggregate_data",
                    models.JSONField(
                        blank=True,
                        default=canonos.evolution.models.default_aggregate_data,
                    ),
                ),
                ("insights", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taste_evolution_snapshots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-snapshot_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["owner", "-snapshot_date"],
                        name="evolution_owner_date_idx",
                    ),
                    models.Index(
                        fields=["owner", "snapshot_period"],
                        name="evolution_owner_period_idx",
                    ),
                ],
            },
        ),
    ]
