# Generated by Codex on 2026-05-04

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BackgroundJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("import", "Import"),
                            ("export", "Export"),
                            ("metadata_refresh", "Metadata refresh"),
                            ("graph_rebuild", "Graph rebuild"),
                            ("narrative_analysis", "Narrative analysis"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("processing", "Processing"),
                            ("complete", "Complete"),
                            ("failed", "Failed"),
                            ("rolled_back", "Rolled back"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="queued",
                        max_length=24,
                    ),
                ),
                ("progress_total", models.PositiveIntegerField(default=0)),
                ("progress_processed", models.PositiveIntegerField(default=0)),
                ("progress_percent", models.PositiveSmallIntegerField(default=0)),
                ("message", models.TextField(blank=True)),
                ("result", models.JSONField(blank=True, default=dict)),
                ("source_id", models.UUIDField(blank=True, null=True)),
                ("source_label", models.CharField(blank=True, max_length=160)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="background_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["owner", "-created_at"], name="job_owner_created_idx"),
                    models.Index(fields=["owner", "status"], name="job_owner_status_idx"),
                    models.Index(fields=["job_type", "source_id"], name="job_type_source_idx"),
                ],
            },
        ),
    ]
