# Generated by Django 5.2.13 on 2026-05-02 00:21

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GraphNode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "node_type",
                    models.CharField(
                        choices=[
                            ("media", "Media"),
                            ("creator", "Creator"),
                            ("dimension", "Dimension"),
                            ("aftertaste_signal", "Aftertaste signal"),
                            ("theme", "Theme"),
                            ("tag", "Tag"),
                            ("medium", "Medium"),
                        ],
                        max_length=32,
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=160)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="graph_nodes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["node_type", "label"],
            },
        ),
        migrations.CreateModel(
            name="GraphEdge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "edge_type",
                    models.CharField(
                        choices=[
                            ("created_by", "Created by"),
                            ("dimension_signal", "Dimension signal"),
                            ("aftertaste_signal", "Aftertaste signal"),
                            ("medium_signal", "Medium signal"),
                            ("tagged_as", "Tagged as"),
                            ("theme_signal", "Theme signal"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(-1),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                ("evidence", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="graph_edges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_edges",
                        to="graph.graphnode",
                    ),
                ),
                (
                    "target_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_edges",
                        to="graph.graphnode",
                    ),
                ),
            ],
            options={
                "ordering": ["edge_type", "source_node__label", "target_node__label"],
            },
        ),
        migrations.AddIndex(
            model_name="graphnode",
            index=models.Index(fields=["owner", "node_type"], name="graph_node_owner_type_idx"),
        ),
        migrations.AddIndex(
            model_name="graphnode",
            index=models.Index(fields=["slug"], name="graph_node_slug_idx"),
        ),
        migrations.AddConstraint(
            model_name="graphnode",
            constraint=models.UniqueConstraint(
                fields=("owner", "node_type", "slug"),
                name="graph_node_owner_type_slug_uniq",
            ),
        ),
        migrations.AddIndex(
            model_name="graphedge",
            index=models.Index(fields=["owner", "edge_type"], name="graph_edge_owner_type_idx"),
        ),
        migrations.AddIndex(
            model_name="graphedge",
            index=models.Index(fields=["source_node"], name="graph_edge_source_idx"),
        ),
        migrations.AddIndex(
            model_name="graphedge",
            index=models.Index(fields=["target_node"], name="graph_edge_target_idx"),
        ),
        migrations.AddConstraint(
            model_name="graphedge",
            constraint=models.UniqueConstraint(
                fields=("owner", "source_node", "target_node", "edge_type"),
                name="graph_edge_owner_nodes_type_uniq",
            ),
        ),
    ]
