# Generated by Django 5.2.13 on 2026-05-03 18:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("graph", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="graphedge",
            name="edge_type",
            field=models.CharField(
                choices=[
                    ("created_by", "Created by"),
                    ("dimension_signal", "Dimension signal"),
                    ("aftertaste_signal", "Aftertaste signal"),
                    ("medium_signal", "Medium signal"),
                    ("tagged_as", "Tagged as"),
                    ("theme_signal", "Theme signal"),
                    ("narrative_signal", "Narrative signal"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="graphnode",
            name="node_type",
            field=models.CharField(
                choices=[
                    ("media", "Media"),
                    ("creator", "Creator"),
                    ("dimension", "Dimension"),
                    ("aftertaste_signal", "Aftertaste signal"),
                    ("theme", "Theme"),
                    ("tag", "Tag"),
                    ("medium", "Medium"),
                    ("narrative_trait", "Narrative trait"),
                ],
                max_length=32,
            ),
        ),
    ]
