# Generated by Django 5.2.13 on 2026-05-03 23:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("graph", "0002_alter_graphedge_edge_type_alter_graphnode_node_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="graphedge",
            index=models.Index(
                fields=["owner", "source_node", "target_node"],
                name="graph_edge_owner_nodes_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="graphedge",
            index=models.Index(fields=["owner", "updated_at"], name="graph_edge_owner_updated_idx"),
        ),
        migrations.AddIndex(
            model_name="graphnode",
            index=models.Index(fields=["owner", "updated_at"], name="graph_node_owner_updated_idx"),
        ),
    ]
