# Generated by Django 5.2.13 on 2026-05-03 19:28

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import canonos.detox.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("media", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DetoxRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("key", models.SlugField(max_length=80)),
                ("name", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True)),
                (
                    "media_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("movie", "Movie"),
                            ("tv_show", "TV show"),
                            ("anime", "Anime"),
                            ("novel", "Novel"),
                            ("audiobook", "Audiobook"),
                        ],
                        max_length=24,
                        null=True,
                    ),
                ),
                ("sample_limit", models.PositiveIntegerField(default=0)),
                (
                    "condition",
                    models.JSONField(blank=True, default=canonos.detox.models.default_condition),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detox_rules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["media_type", "sample_limit", "name"],
            },
        ),
        migrations.CreateModel(
            name="DetoxDecision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("drop", "Drop"),
                            ("pause", "Pause"),
                            ("delay", "Delay"),
                            ("archive", "Archive"),
                            ("continue", "Continue"),
                        ],
                        max_length=16,
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                (
                    "estimated_time_saved_minutes",
                    models.PositiveIntegerField(default=0),
                ),
                ("progress_value", models.PositiveIntegerField(default=0)),
                (
                    "motivation_score",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "media_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detox_decisions",
                        to="media.mediaitem",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="decisions",
                        to="detox.detoxrule",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="detoxrule",
            index=models.Index(fields=["owner", "is_enabled"], name="detox_rule_owner_enabled_idx"),
        ),
        migrations.AddIndex(
            model_name="detoxrule",
            index=models.Index(fields=["owner", "media_type"], name="detox_rule_owner_type_idx"),
        ),
        migrations.AddConstraint(
            model_name="detoxrule",
            constraint=models.UniqueConstraint(
                fields=("owner", "key"), name="detox_rule_owner_key_uniq"
            ),
        ),
        migrations.AddIndex(
            model_name="detoxdecision",
            index=models.Index(fields=["media_item", "-created_at"], name="detox_dec_media_idx"),
        ),
        migrations.AddIndex(
            model_name="detoxdecision",
            index=models.Index(fields=["decision", "-created_at"], name="detox_dec_kind_idx"),
        ),
    ]
