export const API_ROUTES = {
  root: "/",
  health: "/health/",
  authCsrf: "/auth/csrf/",
  authRegister: "/auth/register/",
  authLogin: "/auth/login/",
  authLogout: "/auth/logout/",
  authMe: "/auth/me/",
  authProfile: "/auth/profile/",
  authSettings: "/auth/settings/",
  aftertaste: "/aftertaste/",
  aftertastePrompts: "/aftertaste/prompts/",
  dashboardSummary: "/dashboard/summary/",
  mediaItems: "/media-items/",
  metadataMatches: "/metadata/matches/",
  importPreview: "/imports/preview/",
  exportRequest: "/exports/",
  tasteDimensions: "/taste-dimensions/",
  tasteProfile: "/taste-profile/",
  tasteGraphSummary: "/taste-graph/summary/",
  tasteGraphNodes: "/taste-graph/nodes/",
  tasteGraphEdges: "/taste-graph/edges/",
  tasteGraphRebuild: "/taste-graph/rebuild/",
  candidates: "/candidates/",
  antiGenericRules: "/anti-generic/rules/",
  antiGenericEvaluate: "/anti-generic/evaluate/",
  queueItems: "/queue-items/",
  queueRecalculate: "/queue-items/recalculate/",
  tonightMode: "/queue/tonight/",
  schema: "/schema/",
  swaggerDocs: "/docs/swagger/",
  scalarDocs: "/docs/scalar/",
} as const;

export type ApiRouteKey = keyof typeof API_ROUTES;
export type ApiRoutePath = (typeof API_ROUTES)[ApiRouteKey];
