# Generated by Django 5.2.13 on 2026-05-01 22:41

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("media", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AftertasteEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("worth_time", models.BooleanField(default=True)),
                (
                    "stayed_with_me_score",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ]
                    ),
                ),
                ("felt_alive", models.BooleanField(default=False)),
                ("felt_generic", models.BooleanField(default=False)),
                ("completion_reason", models.CharField(blank=True, max_length=255)),
                ("what_worked", models.TextField(blank=True)),
                ("what_failed", models.TextField(blank=True)),
                ("final_thoughts", models.TextField(blank=True)),
                (
                    "appetite_effect",
                    models.CharField(
                        choices=[
                            ("more_like_this", "More like this"),
                            ("less_like_this", "Less like this"),
                            ("only_in_mood", "Only in the right mood"),
                            ("no_change", "No change"),
                        ],
                        default="no_change",
                        max_length=24,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "media_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aftertaste_entries",
                        to="media.mediaitem",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aftertaste_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["owner", "-created_at"],
                        name="aftertaste_owner_created_idx",
                    ),
                    models.Index(
                        fields=["media_item", "-created_at"],
                        name="aftertaste_media_created_idx",
                    ),
                    models.Index(fields=["appetite_effect"], name="aftertaste_appetite_idx"),
                ],
            },
        ),
    ]
