# Generated by Django 5.2.13 on 2026-05-02 00:33

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("candidates", "0001_initial"),
        ("media", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AntiGenericEvaluation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "genericness_risk_score",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                (
                    "time_waste_risk_score",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                (
                    "positive_exception_score",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                ("detected_signals", models.JSONField(blank=True, default=list)),
                ("positive_exceptions", models.JSONField(blank=True, default=list)),
                (
                    "final_verdict",
                    models.CharField(
                        choices=[
                            ("low_risk", "Low risk"),
                            ("sample_with_guardrail", "Sample with guardrail"),
                            ("likely_generic_skip", "Likely generic skip"),
                            ("modern_exception", "Modern exception"),
                        ],
                        max_length=40,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anti_generic_evaluations",
                        to="candidates.candidate",
                    ),
                ),
                (
                    "media_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="anti_generic_evaluations",
                        to="media.mediaitem",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["candidate", "-created_at"],
                        name="ag_eval_candidate_recent_idx",
                    ),
                    models.Index(fields=["final_verdict"], name="ag_eval_verdict_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="AntiGenericRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("key", models.SlugField(max_length=80)),
                ("name", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True)),
                (
                    "weight",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                ("is_positive_exception", models.BooleanField(default=False)),
                ("is_enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anti_generic_rules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["is_positive_exception", "name"],
                "indexes": [
                    models.Index(fields=["owner", "is_enabled"], name="ag_rule_owner_enabled_idx"),
                    models.Index(fields=["key"], name="ag_rule_key_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("owner", "key"), name="anti_generic_rule_owner_key_uniq"
                    )
                ],
            },
        ),
    ]
